export type WebGitHubRouteKey =
  | 'repoSlug'
  | 'repoUpstream'
  | 'prForBranch'
  | 'issue'
  | 'workItem'
  | 'workItemByOwnerRepo'
  | 'workItemDetails'
  | 'prFileContents'
  | 'listIssues'
  | 'createIssue'
  | 'countWorkItems'
  | 'listWorkItems'
  | 'prChecks'
  | 'prCheckDetails'
  | 'rerunPRChecks'
  | 'prComments'
  | 'setPRCommentReaction'
  | 'resolveReviewThread'
  | 'setPRFileViewed'
  | 'updatePRTitle'
  | 'mergePR'
  | 'markPRReadyForReview'
  | 'setPRAutoMerge'
  | 'updatePRState'
  | 'requestPRReviewers'
  | 'removePRReviewers'
  | 'updateIssue'
  | 'addIssueComment'
  | 'addPRReviewCommentReply'
  | 'addPRReviewComment'
  | 'listLabels'
  | 'listAssignableUsers'
  | 'rateLimit'
  | 'listBindableAccounts'
  | 'validateAccountBinding'
  | 'listAccessibleProjects'
  | 'resolveProjectRef'
  | 'listProjectViews'
  | 'getProjectViewTable'
  | 'projectWorkItemDetailsBySlug'
  | 'updateProjectItemField'
  | 'clearProjectItemField'
  | 'updateIssueBySlug'
  | 'updatePullRequestBySlug'
  | 'addIssueCommentBySlug'
  | 'updateIssueCommentBySlug'
  | 'deleteIssueCommentBySlug'
  | 'listLabelsBySlug'
  | 'listAssignableUsersBySlug'
  | 'listIssueTypesBySlug'
  | 'updateIssueTypeBySlug'

export type WebGitHubRuntimeMethod =
  | 'github.repoSlug'
  | 'github.repoUpstream'
  | 'github.prForBranch'
  | 'github.issue'
  | 'github.workItem'
  | 'github.workItemByOwnerRepo'
  | 'github.workItemDetails'
  | 'github.prFileContents'
  | 'github.listIssues'
  | 'github.createIssue'
  | 'github.countWorkItems'
  | 'github.listWorkItems'
  | 'github.prChecks'
  | 'github.prCheckDetails'
  | 'github.rerunPRChecks'
  | 'github.prComments'
  | 'github.setPRCommentReaction'
  | 'github.resolveReviewThread'
  | 'github.setPRFileViewed'
  | 'github.updatePRTitle'
  | 'github.mergePR'
  | 'github.markPRReadyForReview'
  | 'github.setPRAutoMerge'
  | 'github.updatePRState'
  | 'github.requestPRReviewers'
  | 'github.removePRReviewers'
  | 'github.updateIssue'
  | 'github.addIssueComment'
  | 'github.addPRReviewCommentReply'
  | 'github.addPRReviewComment'
  | 'github.listLabels'
  | 'github.listAssignableUsers'
  | 'github.rateLimit'
  | 'github.listBindableAccounts'
  | 'github.validateAccountBinding'
  | 'github.project.listAccessible'
  | 'github.project.resolveRef'
  | 'github.project.listViews'
  | 'github.project.viewTable'
  | 'github.project.workItemDetailsBySlug'
  | 'github.project.updateItemField'
  | 'github.project.clearItemField'
  | 'github.project.updateIssueBySlug'
  | 'github.project.updatePullRequestBySlug'
  | 'github.project.addIssueCommentBySlug'
  | 'github.project.updateIssueCommentBySlug'
  | 'github.project.deleteIssueCommentBySlug'
  | 'github.project.listLabelsBySlug'
  | 'github.project.listAssignableUsersBySlug'
  | 'github.project.listIssueTypesBySlug'
  | 'github.project.updateIssueTypeBySlug'

export const GITHUB_WEB_RPC_METHODS = {
  repoSlug: 'github.repoSlug',
  repoUpstream: 'github.repoUpstream',
  prForBranch: 'github.prForBranch',
  issue: 'github.issue',
  workItem: 'github.workItem',
  workItemByOwnerRepo: 'github.workItemByOwnerRepo',
  workItemDetails: 'github.workItemDetails',
  prFileContents: 'github.prFileContents',
  listIssues: 'github.listIssues',
  createIssue: 'github.createIssue',
  countWorkItems: 'github.countWorkItems',
  listWorkItems: 'github.listWorkItems',
  prChecks: 'github.prChecks',
  prCheckDetails: 'github.prCheckDetails',
  rerunPRChecks: 'github.rerunPRChecks',
  prComments: 'github.prComments',
  setPRCommentReaction: 'github.setPRCommentReaction',
  resolveReviewThread: 'github.resolveReviewThread',
  setPRFileViewed: 'github.setPRFileViewed',
  updatePRTitle: 'github.updatePRTitle',
  mergePR: 'github.mergePR',
  markPRReadyForReview: 'github.markPRReadyForReview',
  setPRAutoMerge: 'github.setPRAutoMerge',
  updatePRState: 'github.updatePRState',
  requestPRReviewers: 'github.requestPRReviewers',
  removePRReviewers: 'github.removePRReviewers',
  updateIssue: 'github.updateIssue',
  addIssueComment: 'github.addIssueComment',
  addPRReviewCommentReply: 'github.addPRReviewCommentReply',
  addPRReviewComment: 'github.addPRReviewComment',
  listLabels: 'github.listLabels',
  listAssignableUsers: 'github.listAssignableUsers',
  rateLimit: 'github.rateLimit',
  listBindableAccounts: 'github.listBindableAccounts',
  validateAccountBinding: 'github.validateAccountBinding',
  listAccessibleProjects: 'github.project.listAccessible',
  resolveProjectRef: 'github.project.resolveRef',
  listProjectViews: 'github.project.listViews',
  getProjectViewTable: 'github.project.viewTable',
  projectWorkItemDetailsBySlug: 'github.project.workItemDetailsBySlug',
  updateProjectItemField: 'github.project.updateItemField',
  clearProjectItemField: 'github.project.clearItemField',
  updateIssueBySlug: 'github.project.updateIssueBySlug',
  updatePullRequestBySlug: 'github.project.updatePullRequestBySlug',
  addIssueCommentBySlug: 'github.project.addIssueCommentBySlug',
  updateIssueCommentBySlug: 'github.project.updateIssueCommentBySlug',
  deleteIssueCommentBySlug: 'github.project.deleteIssueCommentBySlug',
  listLabelsBySlug: 'github.project.listLabelsBySlug',
  listAssignableUsersBySlug: 'github.project.listAssignableUsersBySlug',
  listIssueTypesBySlug: 'github.project.listIssueTypesBySlug',
  updateIssueTypeBySlug: 'github.project.updateIssueTypeBySlug'
} as const satisfies Record<WebGitHubRouteKey, WebGitHubRuntimeMethod>
