// Why: browser schemas stay separate from handler registration so both sides
// remain under the line cap and dispatch wiring stays scannable.
export {
  Check,
  ClipboardWrite,
  CookieDelete,
  CookieGet,
  CookieSet,
  DialogAccept,
  Drag,
  Element,
  Eval,
  Exec,
  Fill,
  Find,
  FullScreenshot,
  Geolocation,
  Get,
  Goto,
  Highlight,
  InterceptEnable,
  Is,
  KeyboardInsert,
  Keypress,
  LimitParam,
  MouseButton,
  MouseWheel,
  MouseXY,
  ProfileDelete,
  ProfileImportFromBrowser,
  Screencast,
  Screenshot,
  Scroll,
  Select,
  SelectorPath,
  SetCredentials,
  SetDevice,
  SetHeaders,
  SetMedia,
  SetOffline,
  StorageKey,
  StorageKeyValue,
  TabClose,
  TabCurrent,
  TabList,
  TabProfileClone,
  TabSetProfile,
  TabShow,
  TabSwitch,
  Type,
  Upload,
  Viewport,
  Wait
} from '../../../../shared/rpc-contract/browser-params'
export {
  BrowserIdentitySet,
  ProfileCreate
} from '../../../../shared/rpc-contract/browser-identity-params'
