import { getAttachmentLabel } from '@/lib/new-workspace'
import {
  getFullComposerCreateDisabled,
  getQuickComposerCreateDisabled
} from '@/lib/new-workspace-create-gates'
import type { ComposerModel } from './composer-model'
import type { ComposerCardActionProps, ComposerCardSourceProps } from './composer-card-contract'

export function buildComposerCardProps(state: ComposerModel) {
  const {
    advancedOpen,
    agentPrompt,
    attachmentPaths,
    baseBranch,
    branchNameOverride,
    parentWorktreeId,
    createGateMode,
    createError,
    createMultiple,
    creating,
    detectedAgentIds,
    eligibleRepos,
    ephemeralVmRecipeError,
    ephemeralVmRecipes,
    ephemeralVmsEnabled,
    filteredLinkItems,
    folderDetectedAgentIds,
    folderSourceRepos,
    folderCreateDisabled,
    folderTargetConnectInProgress,
    folderTargetConnectionId,
    folderTargetIsRemote,
    folderTargetRequiresConnection,
    folderTargetSshStatus,
    forkPushWarning,
    handleAddAttachment,
    handleBaseBranchChange,
    handleBaseBranchMrSelect,
    handleBaseBranchPrSelect,
    handleBranchNameOverrideChange,
    handleClearSmartNameSelection,
    handleFolderSourceRepoChange,
    handleLinkPopoverChange,
    handleNameValueChange,
    handleOpenAgentSettings,
    handleOpenJiraSettings,
    handleProjectChange,
    handleProjectHostSetupChange,
    handleRemoveLinkedWorkItem,
    handleRepoChange,
    handleReuseSelectedBranchChange,
    handleSelectLinkedItem,
    handleSetupAgentStartupPolicyChange,
    handleSmartBranchSelect,
    handleSmartGitHubItemSelect,
    handleSmartGitLabItemSelect,
    handleSmartJiraIssueSelect,
    handleSmartLinearIssueSelect,
    handleSparseSelectPreset,
    isProjectGroupTarget,
    linkDirectLoading,
    linkItemsLoading,
    linkPopoverOpen,
    linkQuery,
    linkedOnlyTemplatePrompt,
    linkedWorkItem,
    name,
    normalizedLinkQuery,
    note,
    onConnectSelectedProjectGroup,
    onConnectSelectedRepo,
    pathStatusProjectError,
    projectError,
    projectHostSetupOptions,
    projectOptions,
    repoId,
    requiresExplicitSetupChoice,
    resolvedSetupDecision,
    reuseEligibleBranch,
    reuseSelectedBranch,
    selectedEphemeralVmRecipeId,
    selectedProjectHostSetupId,
    selectedProjectId,
    selectedRepo,
    selectedRepoExecutionHostId,
    selectedRepoConnectInProgress,
    selectedRepoConnectionId,
    selectedRepoGitHubSourceContext,
    selectedRepoIsGit,
    selectedRepoProjectId,
    selectedRepoRequiresConnection,
    shouldWaitForIssueAutomationCheck,
    sourceIntentBlocksCreate,
    sparseError,
    selectedRepoSshStatus,
    setAdvancedOpen,
    setAgentPrompt,
    setAttachmentPaths,
    setCreateMultiple,
    setLinkQuery,
    setNote,
    setParentWorktreeId,
    setSelectedEphemeralVmRecipeId,
    setSetupDecision,
    setSmartNameMode,
    setTuiAgent,
    setupAgentStartupPolicy,
    setupConfig,
    setupDecision,
    shouldApplyLinkedOnlyTemplate,
    shouldWaitForSetupCheck,
    workspaceSeedName,
    smartNameJiraSourceContext,
    smartNameMode,
    smartNameSelection,
    sparsePresets,
    sparseSelectedPresetId,
    startFromResetHint,
    submit,
    tuiAgent
  } = state

  const createGateInput = {
    repoId,
    workspaceSeedName,
    creating,
    shouldWaitForSetupCheck,
    shouldWaitForIssueAutomationCheck,
    sourceIntentBlocksCreate,
    requiresExplicitSetupChoice,
    hasSetupDecision: Boolean(setupDecision),
    selectedRepoRequiresConnection,
    sparseError
  }
  const repoCreateDisabled =
    createGateMode === 'quick'
      ? getQuickComposerCreateDisabled(createGateInput)
      : getFullComposerCreateDisabled(createGateInput)
  const createDisabled = isProjectGroupTarget ? folderCreateDisabled : repoCreateDisabled
  const cardProps: ComposerCardSourceProps & ComposerCardActionProps = {
    eligibleRepos: isProjectGroupTarget ? folderSourceRepos : eligibleRepos,
    repoId,
    projectOptions,
    selectedProjectId,
    selectedRepoIsGit: isProjectGroupTarget ? true : selectedRepoIsGit,
    onRepoChange: isProjectGroupTarget ? handleFolderSourceRepoChange : handleRepoChange,
    onProjectChange: handleProjectChange,
    projectHostSetupOptions: isProjectGroupTarget ? [] : projectHostSetupOptions,
    selectedProjectHostSetupId: isProjectGroupTarget ? null : selectedProjectHostSetupId,
    onProjectHostSetupChange: handleProjectHostSetupChange,
    ephemeralVmRecipes: isProjectGroupTarget || !ephemeralVmsEnabled ? [] : ephemeralVmRecipes,
    selectedEphemeralVmRecipeId:
      isProjectGroupTarget || !ephemeralVmsEnabled ? null : selectedEphemeralVmRecipeId,
    onEphemeralVmRecipeChange: setSelectedEphemeralVmRecipeId,
    ephemeralVmRecipeError:
      isProjectGroupTarget || !ephemeralVmsEnabled ? null : ephemeralVmRecipeError,
    repoBackedSearchRepos: isProjectGroupTarget ? folderSourceRepos : undefined,
    repoBackedSourcesDisabled: isProjectGroupTarget ? folderSourceRepos.length === 0 : false,
    allowSmartNameAddProject: !isProjectGroupTarget,
    smartNameRepoSwitchTarget: isProjectGroupTarget ? 'task-source' : 'project',
    name,
    onNameValueChange: handleNameValueChange,
    branchNameOverride: isProjectGroupTarget ? undefined : branchNameOverride,
    onBranchNameOverrideChange: isProjectGroupTarget ? () => {} : handleBranchNameOverrideChange,
    parentWorktreeId: isProjectGroupTarget ? null : parentWorktreeId,
    onParentWorktreeIdChange: isProjectGroupTarget ? () => {} : setParentWorktreeId,
    selectedRepoExecutionHostId: isProjectGroupTarget ? null : selectedRepoExecutionHostId,
    selectedRepoProjectId: isProjectGroupTarget ? null : selectedRepoProjectId,
    onSmartGitHubItemSelect: handleSmartGitHubItemSelect,
    onSmartGitLabItemSelect: handleSmartGitLabItemSelect,
    onSmartBranchSelect: isProjectGroupTarget ? () => {} : handleSmartBranchSelect,
    onSmartNameModeChange: setSmartNameMode,
    onSmartLinearIssueSelect: handleSmartLinearIssueSelect,
    onSmartJiraIssueSelect: handleSmartJiraIssueSelect,
    onOpenJiraSettings: handleOpenJiraSettings,
    smartNameGitHubSourceContext: selectedRepoGitHubSourceContext,
    smartNameJiraSourceContext,
    smartNameMode,
    smartNameSelection,
    onClearSmartNameSelection: handleClearSmartNameSelection,
    canReuseSelectedBranch:
      !isProjectGroupTarget &&
      reuseEligibleBranch !== null &&
      smartNameSelection?.kind === 'branch',
    reuseSelectedBranch,
    onReuseSelectedBranchChange: handleReuseSelectedBranchChange,
    // Why: "create multiple" applies only to worktree (git) targets; folder-workspace keeps create-and-close.
    showCreateMultiple: !isProjectGroupTarget,
    createMultiple,
    onCreateMultipleChange: setCreateMultiple,
    agentPrompt,
    onAgentPromptChange: setAgentPrompt,
    linkedOnlyTemplatePreview: shouldApplyLinkedOnlyTemplate ? linkedOnlyTemplatePrompt : null,
    attachmentPaths,
    getAttachmentLabel,
    onAddAttachment: () => void handleAddAttachment(),
    onRemoveAttachment: (pathValue) =>
      setAttachmentPaths((current) => current.filter((currentPath) => currentPath !== pathValue)),
    linkedWorkItem,
    onRemoveLinkedWorkItem: handleRemoveLinkedWorkItem,
    linkPopoverOpen,
    onLinkPopoverOpenChange: handleLinkPopoverChange,
    linkQuery,
    onLinkQueryChange: setLinkQuery,
    filteredLinkItems,
    linkItemsLoading,
    linkDirectLoading,
    normalizedLinkQuery,
    onSelectLinkedItem: handleSelectLinkedItem,
    tuiAgent,
    onTuiAgentChange: setTuiAgent,
    detectedAgentIds: isProjectGroupTarget ? folderDetectedAgentIds : detectedAgentIds,
    onOpenAgentSettings: handleOpenAgentSettings,
    advancedOpen,
    onToggleAdvanced: () => setAdvancedOpen((current) => !current),
    createDisabled,
    projectError: isProjectGroupTarget ? pathStatusProjectError : projectError,
    creating,
    onCreate: () => void submit(),
    baseBranch: isProjectGroupTarget ? undefined : baseBranch,
    onBaseBranchChange: isProjectGroupTarget ? () => {} : handleBaseBranchChange,
    onBaseBranchPrSelect: isProjectGroupTarget ? () => {} : handleBaseBranchPrSelect,
    onBaseBranchMrSelect: isProjectGroupTarget ? () => {} : handleBaseBranchMrSelect,
    baseBranchLinkedPrNumber:
      linkedWorkItem?.type === 'pr' && baseBranch ? linkedWorkItem.number : null,
    selectedRepoPath: isProjectGroupTarget ? null : (selectedRepo?.path ?? null),
    selectedRepoIsRemote: isProjectGroupTarget
      ? folderTargetIsRemote
      : Boolean(selectedRepo?.connectionId),
    selectedRepoConnectionId: isProjectGroupTarget
      ? folderTargetConnectionId
      : selectedRepoConnectionId,
    selectedRepoSshStatus: isProjectGroupTarget ? folderTargetSshStatus : selectedRepoSshStatus,
    selectedRepoRequiresConnection: isProjectGroupTarget
      ? folderTargetRequiresConnection
      : selectedRepoRequiresConnection,
    selectedRepoConnectInProgress: isProjectGroupTarget
      ? folderTargetConnectInProgress
      : selectedRepoConnectInProgress,
    onConnectSelectedRepo: isProjectGroupTarget
      ? onConnectSelectedProjectGroup
      : onConnectSelectedRepo,
    startFromResetHint: isProjectGroupTarget ? null : startFromResetHint,
    forkPushWarning: isProjectGroupTarget ? null : forkPushWarning,
    note,
    onNoteChange: setNote,
    setupConfig: isProjectGroupTarget ? null : setupConfig,
    requiresExplicitSetupChoice: isProjectGroupTarget ? false : requiresExplicitSetupChoice,
    setupDecision: isProjectGroupTarget ? null : setupDecision,
    onSetupDecisionChange: isProjectGroupTarget ? () => {} : setSetupDecision,
    setupAgentStartupPolicy: isProjectGroupTarget ? 'start-immediately' : setupAgentStartupPolicy,
    onSetupAgentStartupPolicyChange: isProjectGroupTarget
      ? () => {}
      : handleSetupAgentStartupPolicyChange,
    shouldWaitForSetupCheck: isProjectGroupTarget ? false : shouldWaitForSetupCheck,
    resolvedSetupDecision: isProjectGroupTarget ? null : resolvedSetupDecision,
    createError,
    canUseSparseCheckout: isProjectGroupTarget
      ? false
      : selectedRepoIsGit && !selectedRepo?.connectionId,
    sparsePresets: isProjectGroupTarget ? [] : sparsePresets,
    sparseSelectedPresetId: isProjectGroupTarget ? null : sparseSelectedPresetId,
    onSparseSelectPreset: isProjectGroupTarget ? () => {} : handleSparseSelectPreset,
    branchesEnabled: !isProjectGroupTarget,
    setupControlsEnabled: !isProjectGroupTarget,
    sparseControlsEnabled: !isProjectGroupTarget
  }

  return { cardProps, createDisabled }
}
