allowBuilds:
  esbuild: true

minimumReleaseAge: 4320

overrides:
  xcode>uuid: 11.1.1
  query-string: 9.5.1

patchedDependencies:
  expo-notifications@55.0.27: patches/expo-notifications@55.0.27.patch
  query-string@9.5.1: patches/query-string@9.5.1.patch
  react-native-webview@13.16.2: patches/react-native-webview@13.16.2.patch
  react-native@0.83.10: patches/react-native@0.83.10.patch
