export function getPiAgentStatusPostQueueSourceLines(): string[] {
  return [
    'type HookPost = { hookEventName: string; extra: Record<string, unknown>; metadata: Record<string, unknown>; ompRuntime: boolean; revision: number; attempts: number; delivered: boolean }',
    'let activePost = false',
    'let pendingPost: HookPost | null = null',
    'let latestPost: HookPost | null = null',
    '// A newer snapshot or session boundary retires every older retry.',
    'let postRevision = 0',
    'let retryTimer: ReturnType<typeof setTimeout> | null = null',
    '',
    'function cancelPostRetry(): void {',
    '  if (retryTimer !== null) clearTimeout(retryTimer)',
    '  retryTimer = null',
    '}',
    '',
    'function resetPostQueue(): void {',
    '  cancelPostRetry()',
    '  postRevision++',
    '  pendingPost = null',
    '  latestPost = null',
    '}',
    '',
    'function drainPosts(): void {',
    '  if (activePost || !pendingPost) return',
    '  const next = pendingPost',
    '  pendingPost = null',
    '  activePost = true',
    '  void postOnce(next.hookEventName, next.extra, next.metadata, next.ompRuntime)',
    '    .then(() => { next.delivered = true })',
    '    .catch(() => {',
    '      if (!next.ompRuntime || next.revision !== postRevision) return',
    '      if (next.attempts >= 3) {',
    "        console.warn('[orca-pi-status] hook delivery failed after retries:', next.hookEventName)",
    '        return',
    '      }',
    '      const delay = 250 * 2 ** next.attempts++',
    '      retryTimer = setTimeout(() => {',
    '        retryTimer = null',
    '        if (next.revision !== postRevision) return',
    '        pendingPost = next',
    '        drainPosts()',
    '      }, delay)',
    "      if (typeof retryTimer.unref === 'function') retryTimer.unref()",
    '    })',
    '    .finally(() => {',
    '      activePost = false',
    '      drainPosts()',
    '    })',
    '}',
    ''
  ]
}
