export function getPiAgentStatusWslCurlSourceLines(): string[] {
  return [
    '// Why: WSL-ness and curl.exe presence cannot change within a process',
    '// lifetime; re-probing /proc and /mnt/c on every failed event would add',
    '// filesystem work to the per-event path.',
    'let cachedIsWslRuntime: boolean | null = null',
    'let cachedWindowsCurlPath: string | null | undefined',
    '',
    'function isWslRuntime(): boolean {',
    '  if (cachedIsWslRuntime !== null) return cachedIsWslRuntime',
    '  cachedIsWslRuntime = detectWslRuntime()',
    '  return cachedIsWslRuntime',
    '}',
    '',
    'function detectWslRuntime(): boolean {',
    '  if (process.env.WSL_DISTRO_NAME) return true',
    '  try {',
    "    const fs = require('fs')",
    "    for (const path of ['/proc/sys/kernel/osrelease', '/proc/version']) {",
    '      try {',
    "        const contents = String(fs.readFileSync(path, 'utf8'))",
    '        if (/microsoft|wsl/i.test(contents)) return true',
    '      } catch {',
    '        // Why: probe the next runtime hint when a proc file is absent or unreadable.',
    '      }',
    '    }',
    '  } catch {',
    '    return false',
    '  }',
    '  return false',
    '}',
    '',
    'function resolveWindowsCurlPath(): string | null {',
    '  if (cachedWindowsCurlPath !== undefined) return cachedWindowsCurlPath',
    '  try {',
    "    const fs = require('fs')",
    "    const curlPath = '/mnt/c/Windows/System32/curl.exe'",
    '    cachedWindowsCurlPath = fs.existsSync(curlPath) ? curlPath : null',
    '  } catch {',
    '    cachedWindowsCurlPath = null',
    '  }',
    '  return cachedWindowsCurlPath',
    '}',
    '',
    '// Why: WSL loopback is not the Windows loopback, so use curl.exe on the host.',
    'async function postViaWindowsCurl(body: string, ompRuntime: boolean): Promise<void> {',
    '  const curlPath = resolveWindowsCurlPath()',
    '  const windowsPort = process.env.ORCA_AGENT_HOOK_PORT',
    '  const windowsToken = process.env.ORCA_AGENT_HOOK_TOKEN',
    "  if (!curlPath || !windowsPort || !windowsToken) throw new Error('Orca WSL hook bridge unavailable')",
    '  // Why: a stale guest endpoint must fall back to current host coordinates.',
    '  const windowsUrl = `http://127.0.0.1:${windowsPort}${resolveHookPath(ompRuntime)}`',
    '  await new Promise<void>((resolve, reject) => {',
    "    const { spawn } = require('child_process')",
    '    const child = spawn(',
    '      curlPath,',
    '      [',
    "        '-sS', '--fail',",
    '        // WSL interop needs a bounded, acknowledged delivery window.',
    "        '--connect-timeout', '3',",
    "        '--max-time', '10',",
    "        '--noproxy', '127.0.0.1',",
    "        '-o', 'NUL',",
    "        '-X', 'POST',",
    "        '-H', 'Content-Type: application/json',",
    "        '-H', `X-Orca-Agent-Hook-Token: ${windowsToken}`,",
    "        '--data-binary', '@-',",
    '        windowsUrl',
    '      ],',
    "      { stdio: ['pipe', 'ignore', 'ignore'] }",
    '    )',
    '    const timer = setTimeout(() => {',
    '      try { child.kill() } catch {}',
    "      reject(new Error('Orca WSL hook delivery timed out'))",
    '    }, 11000)',
    "    if (typeof timer.unref === 'function') timer.unref()",
    '    const fail = (error: Error): void => { clearTimeout(timer); reject(error) }',
    "    child.on('error', fail)",
    "    child.stdin.on('error', fail)",
    "    child.on('close', (code: number | null) => {",
    '      clearTimeout(timer)',
    "      if (code === 0) resolve(); else reject(new Error('Orca WSL hook exit ' + code))",
    '    })',
    '    child.stdin.end(body)',
    '  })',
    '}',
    ''
  ]
}
