import { getPiAgentStatusPostQueueSourceLines } from './agent-status-post-queue-source'
// Why: pi has no settings.json hook surface — its extensibility is the
// in-process TypeScript extension API (pi.on('agent_start'), 'tool_call',
// etc.). To get pi panes into the unified agent-hooks pipeline alongside
// Claude/Codex/Gemini/OpenCode/Cursor, we ship a bundled extension into
// the selected Pi/OMP extension dir (PiTitlebarExtensionService) that POSTs to
// /hook/<kind> using the same ORCA_AGENT_HOOK_* + ORCA_PANE_KEY env that every
// PTY already receives from ipc/pty.ts.
//
// Each Pi process gets its own paneKey through env. Like the OpenCode plugin,
// the returned source is a string (loaded by jiti from disk inside the pi process), so we
// keep the source body in plain JS without TS types and avoid pulling pi or
// any Orca dep into the pi runtime.
import type { PiAgentKind } from '../../shared/pi-agent-kind'
import { getPiAgentStatusHandlerSourceLines } from './agent-status-handler-source'
import { getPiAgentStatusRuntimeDetectionSourceLines } from './agent-status-runtime-detection-source'
import { getPiAgentStatusWslCurlSourceLines } from './agent-status-wsl-curl-source'

export const ORCA_PI_AGENT_STATUS_EXTENSION_FILE = 'orca-agent-status.ts'

/** Source of the status extension installed into a Pi-family agent's extension
 *  dir: it POSTs lifecycle, tool, and (under OMP) model events to Orca's hook
 *  endpoint. Returned as one self-contained string — it runs inside the agent. */
export function getPiAgentStatusExtensionSource(kind: PiAgentKind = 'pi'): string {
  // OMP resumes by id; its persistent file path lets native chat skip discovery.
  const sessionMetadataSourceLines =
    kind !== 'omp'
      ? [
          'let sessionMetadata: Record<string, unknown> = {}',
          'let runtimeOmpSessionMetadata: Record<string, unknown> = {}',
          '',
          'function updateSessionMetadata(ctx: unknown): void {',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  sessionMetadata = typeof sessionId === 'string' && sessionId ? {",
          '    session_id: sessionId,',
          "    ...(typeof sessionFile === 'string' && sessionFile ? { session_file: sessionFile } : {}),",
          '  } : {}',
          '}',
          '',
          'function updateRuntimeOmpSessionMetadata(ctx: unknown): void {',
          '  if (!isOmpRuntime()) return',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  runtimeOmpSessionMetadata = typeof sessionId === 'string' && sessionId && typeof sessionFile === 'string' && sessionFile ? { session_id: sessionId, session_file: sessionFile } : {}",
          '  trackModelSession(runtimeOmpSessionMetadata.session_id)',
          '  updateModelMetadata(ctx)',
          '}',
          '',
          'function getPostSessionMetadata(ompRuntime: boolean): Record<string, unknown> {',
          '  return ompRuntime ? { ...runtimeOmpSessionMetadata, ...modelMetadata } : sessionMetadata',
          '}',
          '',
          'function getPersistedSessionMetadata(): Record<string, unknown> {',
          '  const sessionFile = sessionMetadata.session_file',
          "  if (typeof sessionFile !== 'string' || !sessionFile) return {}",
          '  try {',
          "    const fs = require('fs')",
          '    // Why: Pi publishes its planned path before creating the transcript;',
          '    // recheck on every post so the first completed turn becomes resumable.',
          '    return fs.existsSync(sessionFile) ? sessionMetadata : {}',
          '  } catch {',
          '    return {}',
          '  }',
          '}',
          ''
        ]
      : [
          'let sessionMetadata: Record<string, unknown> = {}',
          '',
          'function updateSessionMetadata(ctx: unknown): void {',
          '  const sessionManager = (ctx as { sessionManager?: { getSessionId?: () => unknown; getSessionFile?: () => unknown } } | null)?.sessionManager',
          '  const sessionId = sessionManager?.getSessionId?.()',
          '  const sessionFile = sessionManager?.getSessionFile?.()',
          "  sessionMetadata = typeof sessionId === 'string' && sessionId && typeof sessionFile === 'string' && sessionFile ? { session_id: sessionId, session_file: sessionFile } : {}",
          '  trackModelSession(sessionMetadata.session_id)',
          '}',
          '',
          'function updateRuntimeOmpSessionMetadata(ctx: unknown): void {',
          '  updateSessionMetadata(ctx)',
          '  updateModelMetadata(ctx)',
          '}',
          '',
          'function getPostSessionMetadata(_ompRuntime: boolean): Record<string, unknown> {',
          '  return { ...sessionMetadata, ...modelMetadata }',
          '}',
          ''
        ]
  // Why: OMP emits no model_select of its own, so the active model is re-read from
  // the event context on every post; the pane's status then always carries it.
  // Reported only under the OMP runtime — Pi has no chat surface consuming it yet.
  const modelMetadataSourceLines = [
    'let modelMetadata: Record<string, unknown> = {}',
    'let ompModelSwitchSupported = false',
    'let modelSessionId: unknown = undefined',
    '',
    '// Why: OMP switches sessions in-process; a model belongs to the session that',
    '// reported it, so it must not leak onto the first posts of the next one.',
    'function trackModelSession(sessionId: unknown): void {',
    '  if (sessionId === modelSessionId) return',
    '  modelSessionId = sessionId',
    '  modelMetadata = {}',
    '}',
    '',
    '// Why: pi and OMP expose the active model as { provider, id } on both the event',
    '// context and model_select events; the joined selector is what --model accepts.',
    'function updateModelMetadata(source: unknown): void {',
    '  try {',
    "    if (!source || typeof source !== 'object' || !('model' in source)) return",
    '    const model = source.model',
    "    if (!model || typeof model !== 'object') return",
    "    const provider = 'provider' in model && typeof model.provider === 'string' ? model.provider : ''",
    "    const id = 'id' in model && typeof model.id === 'string' ? model.id : ''",
    "    if (provider && id) modelMetadata = { model: provider + '/' + id, ...(ompModelSwitchSupported ? { model_switch_command: 'orca-model' } : {}) }",
    '  } catch {',
    '    // Why: a throwing model getter must never break status delivery.',
    '  }',
    '}'
  ]

  // Why: Pi resumes from an existing transcript; OMP resumes directly by session id (#8962).
  const payloadLine =
    kind !== 'omp'
      ? '    payload: { hook_event_name: hookEventName, ...(ompRuntime ? metadata : getPersistedSessionMetadata()), ...extra },'
      : '    payload: { hook_event_name: hookEventName, ...metadata, ...extra },'

  // Why: keep this string self-contained — it runs inside the pi process,
  // so it cannot import from Orca's main bundle. fs/http coords come from
  // the same endpoint file the OpenCode plugin reads (process.env is frozen
  // at PTY spawn, so on Orca restart we have to re-read it from disk).
  return [
    '// Why: no package-specific type import here. Pi and OMP expose the same',
    '// extension API, but publish their types under different package names.',
    '// Why: warn-once so a recurring parse error on a malformed endpoint',
    '// file does not spam stderr inside the pi TUI on every event.',
    'let warnedBadEndpoint = false',
    '// Why: Pi awaits extension handlers. Status delivery stays off that',
    '// critical path, and the latest-only pending slot prevents a stalled',
    '// Orca receiver from building an unbounded queue of obsolete snapshots.',
    'const HOOK_POST_TIMEOUT_MS = 1000',
    ...getPiAgentStatusPostQueueSourceLines(),
    ...(kind === 'pi' ? ['let piUiPromptDepth = 0', 'let piTurnInFlight = false'] : []),
    ...modelMetadataSourceLines,
    '',
    ...sessionMetadataSourceLines,
    '',
    '// Why: re-reading the endpoint file on every event is cheap (small file,',
    '// rare changes) but stat+mtime caching avoids re-parsing on every event',
    '// during streaming tool execution. Mirrors the OpenCode plugin cache shape.',
    "let cachedEndpointKey = ''",
    'let cachedEndpointValues: Record<string, string> | null = null',
    '',
    'function readEndpointFile(): Record<string, string> | null {',
    '  const path = process.env.ORCA_AGENT_HOOK_ENDPOINT',
    '  if (!path) return null',
    '  try {',
    "    const fs = require('fs')",
    '    try {',
    '      const stat = fs.statSync(path)',
    "      const cacheKey = stat.mtimeMs + ':' + stat.size + ':' + stat.ino",
    '      if (cacheKey === cachedEndpointKey && cachedEndpointValues) {',
    '        return cachedEndpointValues',
    '      }',
    "      const contents: string = fs.readFileSync(path, 'utf8')",
    '      const out: Record<string, string> = {}',
    '      for (const line of contents.split(/\\r?\\n/)) {',
    '        // Why: parse `KEY=VALUE` (POSIX endpoint.env) and `set KEY=VALUE`',
    '        // (Windows endpoint.cmd) with one regex; strip a trailing CR so',
    '        // mixed-EOL files do not leak \\r into the value.',
    '        const m = line.match(/^(?:set\\s+)?([A-Z0-9_]+)=(.*)$/)',
    "        if (m) out[m[1]] = m[2].replace(/\\r$/, '')",
    '      }',
    '      cachedEndpointKey = cacheKey',
    '      cachedEndpointValues = out',
    '      return out',
    '    } catch (ioErr) {',
    "      cachedEndpointKey = ''",
    '      cachedEndpointValues = null',
    '      throw ioErr',
    '    }',
    '  } catch (err: unknown) {',
    '    const code = (err as { code?: string } | null)?.code',
    "    if (err && code !== 'ENOENT' && !warnedBadEndpoint) {",
    '      warnedBadEndpoint = true',
    "      console.warn('[orca-pi-status] failed to parse endpoint file:', (err as Error).message)",
    '    }',
    '    return null',
    '  }',
    '}',
    '',
    'function resolveHookCoords() {',
    '  const fileEnv = readEndpointFile() || {}',
    '  return {',
    '    port: fileEnv.ORCA_AGENT_HOOK_PORT || process.env.ORCA_AGENT_HOOK_PORT,',
    '    token: fileEnv.ORCA_AGENT_HOOK_TOKEN || process.env.ORCA_AGENT_HOOK_TOKEN,',
    "    env: fileEnv.ORCA_AGENT_HOOK_ENV || process.env.ORCA_AGENT_HOOK_ENV || '',",
    "    version: fileEnv.ORCA_AGENT_HOOK_VERSION || process.env.ORCA_AGENT_HOOK_VERSION || '',",
    '  }',
    '}',
    '',
    ...getPiAgentStatusRuntimeDetectionSourceLines(kind),
    '',
    'function post(hookEventName: string, extra: Record<string, unknown> = {}): void {',
    '  const ompRuntime = isOmpRuntime()',
    '  cancelPostRetry()',
    '  const metadata = getPostSessionMetadata(ompRuntime)',
    '// Model changes must not erase an unacknowledged completion in the latest-only slot.',
    "  const previousCompletion = latestPost?.hookEventName === 'agent_end' && !latestPost.delivered && latestPost.metadata.session_id === metadata.session_id",
    '  pendingPost = {',
    '    revision: ++postRevision,',
    '    attempts: 0,',
    '    delivered: false,',
    "    hookEventName: ompRuntime && hookEventName === 'model_select' && previousCompletion ? 'agent_end' : hookEventName,",
    // Why: every coalesced snapshot must retain an open modal, not just its start event.
    kind === 'pi'
      ? '    extra: { ...extra, ...(!ompRuntime && piUiPromptDepth > 0 ? { ui_prompt_active: true } : {}) },'
      : '    extra,',
    '    metadata,',
    '    ompRuntime,',
    '  }',
    '  latestPost = pendingPost',
    '  drainPosts()',
    '}',
    '',
    'async function postOnce(',
    '  hookEventName: string,',
    '  extra: Record<string, unknown>,',
    '  metadata: Record<string, unknown>,',
    '  ompRuntime: boolean',
    '): Promise<void> {',
    '  const coords = resolveHookCoords()',
    '  const paneKey = process.env.ORCA_PANE_KEY',
    '  if (!coords.port || !coords.token || !paneKey) return',
    '  const url = `http://127.0.0.1:${coords.port}${resolveHookPath(ompRuntime)}`',
    '  const body = JSON.stringify({',
    '    paneKey,',
    "    launchToken: process.env.ORCA_AGENT_LAUNCH_TOKEN || '',",
    "    tabId: process.env.ORCA_TAB_ID || '',",
    "    worktreeId: process.env.ORCA_WORKTREE_ID || '',",
    '    env: coords.env,',
    '    version: coords.version,',
    payloadLine,
    '  })',
    "  const controller = typeof AbortController !== 'undefined' ? new AbortController() : null",
    '  let timeout: ReturnType<typeof setTimeout> | undefined',
    '  const timeoutPromise = new Promise<never>((_resolve, reject) => {',
    '    timeout = setTimeout(() => {',
    '      controller?.abort()',
    "      reject(new Error('Orca hook delivery timed out'))",
    '    }, HOOK_POST_TIMEOUT_MS)',
    "    if (typeof timeout.unref === 'function') timeout.unref()",
    '  })',
    '  try {',
    '    const response = await Promise.race([',
    '      fetch(url, {',
    "        method: 'POST',",
    '        headers: {',
    "          'Content-Type': 'application/json',",
    "          'X-Orca-Agent-Hook-Token': coords.token,",
    '        },',
    '        body,',
    '        ...(controller ? { signal: controller.signal } : {}),',
    '      }),',
    '      timeoutPromise,',
    '    ])',
    "    if (!response.ok) throw new Error('Orca hook HTTP ' + response.status)",
    '  } catch (error) {',
    '    // Why: status reporting must never fail the pi run just because Orca',
    '    // is unavailable or the loopback request failed (e.g. Orca restart).',
    '    if (!isWslRuntime()) throw error',
    '    await postViaWindowsCurl(body, ompRuntime)',
    '  } finally {',
    '    if (timeout) clearTimeout(timeout)',
    '  }',
    '}',
    '',
    ...getPiAgentStatusWslCurlSourceLines(),
    ...getPiAgentStatusHandlerSourceLines(kind)
  ].join('\n')
}
