// OMP loads the same extension in each in-process task session.
export function getOmpSessionOwnerHandlerSourceLines(): string[] {
  return [
    '  // SessionManager survives reload/new/resume; task children own a different instance.',
    '  function sessionProvenance(ctx): { manager: unknown; id?: string; file?: string; parent?: string } | undefined {',
    '    const manager = ctx?.sessionManager',
    "    if (!manager || typeof manager !== 'object') return undefined",
    '    const id = typeof manager.getSessionId === "function" ? manager.getSessionId() : undefined',
    '    const file = typeof manager.getSessionFile === "function" ? manager.getSessionFile() : undefined',
    '    const header = typeof manager.getHeader === "function" ? manager.getHeader() : undefined',
    '    return { manager, id, file, parent: typeof header?.parentSession === "string" ? header.parentSession : undefined }',
    '  }',
    '',
    '  function normalizeSessionPath(file): string {',
    '    const normalized = file.replace(/\\\\/g, "/")',
    '    return /^[A-Za-z]:\\//.test(normalized) ? normalized.toLowerCase() : normalized',
    '  }',
    '',
    '  function isNestedTaskTranscript(parentFile, candidateFile): boolean {',
    '    if (typeof parentFile !== "string" || typeof candidateFile !== "string") return false',
    '    const parent = normalizeSessionPath(parentFile)',
    '    const candidate = normalizeSessionPath(candidateFile)',
    '    const root = parent.endsWith(".jsonl") ? parent.slice(0, -6) : parent',
    '    return candidate.startsWith(`${root}/`) && candidate !== parent',
    '  }',
    '',
    '  function ownsSessionStatus(ctx): boolean {',
    '    if (!isOmpRuntime()) return true',
    '    // Newer OMP builds may expose this computed runtime provenance directly.',
    '    if (ctx?.agentKind === "sub") return false',
    '    const current = sessionProvenance(ctx)',
    '    if (!current) return true',
    "    // A task transcript is never the pane's resumable root, even when its",
    '    // callback arrives before the root session reports on the shared hook.',
    '    if (current.parent) return false',
    '    // Keep ownership through module reload and shutdown while child sessions drain.',
    "    const key = Symbol.for('orca.omp.status-session-owners')",
    '    let owners = Reflect.get(globalThis, key)',
    '    if (!(owners instanceof Map)) {',
    '      owners = new Map()',
    '      Reflect.set(globalThis, key, owners)',
    '    }',
    '    const pane = JSON.stringify([process.env.ORCA_PANE_KEY, process.env.ORCA_AGENT_LAUNCH_TOKEN])',
    '    const owner = owners.get(pane)',
    '    if (owner) {',
    '      if (owner.manager === current.manager) return true',
    '      if (current.parent === owner.file || current.parent === owner.id) return false',
    '      if (isNestedTaskTranscript(owner.file, current.file)) return false',
    '      return false',
    '    }',
    '    owners.set(pane, current)',
    '    return true',
    '  }',
    '',
    '  function onStatus(name, handler): void {',
    '    pi.on(name, (event, ctx) => {',
    '      if (!ownsSessionStatus(ctx)) return',
    '      return handler(event, ctx)',
    '    })',
    '  }',
    '',
    "  onStatus('session_start', () => {})",
    ''
  ]
}
