// SDKMessage discriminators from Claude Agent SDK 0.3.251 / Claude Code 2.1.258.
export const CLAUDE_STREAM_JSON_FRAME_KINDS = [
  'message:assistant',
  'message:user',
  'message:result',
  'message:system:init',
  'message:stream_event:message_start',
  'message:stream_event:message_delta',
  'message:stream_event:message_stop',
  'message:stream_event:content_block_start',
  'message:stream_event:content_block_delta',
  'message:stream_event:content_block_stop',
  'message:system:compact_boundary',
  'message:system:status',
  'message:system:api_retry',
  'message:system:control_request_progress',
  'message:system:model_refusal_fallback',
  'message:system:model_refusal_no_fallback',
  'message:system:local_command_output',
  'message:system:hook_started',
  'message:system:hook_progress',
  'message:system:hook_response',
  'message:system:plugin_install',
  'message:tool_progress',
  'message:auth_status',
  'message:system:task_notification',
  'message:system:task_started',
  'message:system:task_updated',
  'message:system:task_progress',
  'message:system:background_tasks_changed',
  'message:system:thinking_tokens',
  'message:system:session_state_changed',
  'message:system:worker_shutting_down',
  'message:system:commands_changed',
  'message:system:notification',
  'message:system:files_persisted',
  'message:tool_use_summary',
  'message:system:memory_recall',
  'message:rate_limit_event',
  'message:system:elicitation_complete',
  'message:system:permission_denied',
  'message:prompt_suggestion',
  'message:system:mirror_error',
  'message:system:informational',
  'message:conversation_reset',
  // Queue bookkeeping the CLI emits per client-supplied command uuid. Absent
  // from the SDK's SDKMessage union, which is why it reached users as raw JSON.
  'message:command_lifecycle',
  'message:result:success',
  'message:result:error_during_execution',
  'message:result:error_max_turns',
  'message:result:error_max_budget_usd',
  'message:result:error_max_structured_output_retries'
] as const

export type ClaudeStreamJsonFrameKind = (typeof CLAUDE_STREAM_JSON_FRAME_KINDS)[number]
