import { ORCHESTRATION_FEDERATION_CONTROL_METHODS } from './federation-control'
import { ORCHESTRATION_FEDERATION_RELAY_METHODS } from './federation-relay'
import { ORCHESTRATION_FEDERATION_ATTACH_METHODS } from './federation'

export const ORCHESTRATION_FEDERATION_METHODS = [
  ...ORCHESTRATION_FEDERATION_ATTACH_METHODS,
  ...ORCHESTRATION_FEDERATION_RELAY_METHODS,
  ...ORCHESTRATION_FEDERATION_CONTROL_METHODS
]
