import type { GlobalSettings } from '../../../../shared/global-settings-types'

export const SETTING_LABELS: Partial<Record<keyof GlobalSettings, string>> = {
  terminalFontSize: 'Font Size',
  terminalFontFamily: 'Font Family',
  editorFontFamily: 'Editor Font Family',
  terminalFontWeight: 'Font Weight',
  terminalLineHeight: 'Line Height',
  terminalScrollSensitivity: 'Normal Scroll Speed',
  terminalFastScrollSensitivity: 'Fast Scroll Speed',
  terminalTuiScrollSensitivity: 'TUI Scroll Speed',
  terminalBackgroundOpacity: 'Background Opacity',
  terminalMinimumContrastRatio: 'Color Contrast',
  terminalCursorStyle: 'Cursor Style',
  terminalCursorBlink: 'Cursor Blink',
  terminalCursorOpacity: 'Cursor Opacity',
  terminalMouseHideWhileTyping: 'Mouse Hide While Typing',
  terminalInlineImages: 'Inline Images',
  terminalWordSeparator: 'Word Separator',
  primarySelectionMiddleClickPaste: 'Middle-click Paste from Selection',
  terminalFocusFollowsMouse: 'Focus Follows Mouse',
  terminalColorOverrides: 'Color Overrides',
  terminalMacOptionAsAlt: 'Option as Alt',
  terminalPaddingX: 'Padding X',
  terminalPaddingY: 'Padding Y',
  terminalDividerColorDark: 'Divider Color (Dark)',
  terminalDividerColorLight: 'Divider Color (Light)',
  terminalInactivePaneOpacity: 'Inactive Pane Opacity',
  windowBackgroundBlur: 'Window Background Blur'
}
