import type { AddWorktreeOptions } from './git/worktree'
import { discardPreparedWorktree } from './git/worktree-create-preparation'
import { isOrphanedWorktreeError } from './ipc/worktree-logic'

// Stale cleanup only reclaims preparations whose owner pid is dead, so a discard that fails inside
// the live process would strand its scratch checkout until the app restarts. Remember the failure
// and retry it on the next preparation for the same host.
const PREPARATION_DISCARD_ATTEMPT_LIMIT = 3

export type PreparationDiscardTarget = {
  hostKey: string
  repoPath: string
  preparedPath: string
  options: AddWorktreeOptions
}

const pendingDiscards = new Map<string, PreparationDiscardTarget & { attempts: number }>()
const inFlightDiscards = new Set<Promise<unknown>>()

/** Keeps a fire-and-forget discard settleable by the test reset, which would otherwise race it. */
export function trackPreparationDiscard(work: Promise<void>): void {
  inFlightDiscards.add(work)
  void work.finally(() => inFlightDiscards.delete(work))
}

function pendingKey(target: PreparationDiscardTarget): string {
  // Paths are generated by this process, so exact equality already identifies the preparation.
  return `${target.hostKey}\0${target.preparedPath}`
}

async function runDiscard(target: PreparationDiscardTarget, attempts: number): Promise<void> {
  try {
    await discardPreparedWorktree(target.repoPath, target.preparedPath, target.options)
  } catch (error) {
    // An aborted or failed checkout self-discards first, so the registration is usually already
    // gone by the time the pool discards; retrying that would only spawn Git to fail again.
    if (isOrphanedWorktreeError(error)) {
      return
    }
    // Bounded: a path that never becomes removable must not tax every later preparation.
    if (attempts >= PREPARATION_DISCARD_ATTEMPT_LIMIT) {
      console.warn(
        `[worktree-create] prepared checkout could not be discarded in ${attempts} attempts; ${target.preparedPath} stays registered until this process exits`,
        error
      )
      return
    }
    pendingDiscards.set(pendingKey(target), { ...target, attempts })
  }
}

/** Never rejects. Records the target for a later retry when the discard fails. */
export function discardPreparationWithRetry(
  target: PreparationDiscardTarget,
  attempts = 1
): Promise<void> {
  // Claim the record so an overlapping retry pass cannot run the same discard twice.
  pendingDiscards.delete(pendingKey(target))
  const discard = runDiscard(target, attempts)
  trackPreparationDiscard(discard)
  return discard
}

export function retryPendingPreparationDiscards(hostKey: string): Promise<void> {
  const pending = [...pendingDiscards.values()].filter((target) => target.hostKey === hostKey)
  return Promise.all(
    pending.map(({ attempts, ...target }) => discardPreparationWithRetry(target, attempts + 1))
  ).then(() => undefined)
}

/** Test-only: settle the fire-and-forget discards before dropping the registry. */
export async function resetPendingPreparationDiscardsForTests(): Promise<void> {
  while (inFlightDiscards.size > 0) {
    await Promise.all(inFlightDiscards)
  }
  pendingDiscards.clear()
}
